### ISSUE TITLE
Neutral Button

### ISSUE THREAD

**Issue by filol** [blennerSilva/AwesomeDialog#1]
Hi,
Can you add a neutral button for AwesomeInfoDialog?
good work ! ;)

**Comment by blennerSilva** [comment]
ok i will do it on next release, just tell me what a neutral button is lol

**Comment by filol** [comment]
It's the button between Negative and Positive button.

https://stackoverflow.com/questions/11401951/android-difference-between-positive-negative-and-neutral-button
