### ISSUE TITLE
Not able to add this dependency in my gradle.

### ISSUE THREAD

**Issue by akshaykumar0291** [blennerSilva/AwesomeDialog#11]
Hi, my android studio version is 3.0.1 and it showing me this message
Failed to resolve: com.github.blennerSilva:AwesomeDialog:2.0.5

**Comment by blennerSilva** [comment]
did u add the jitpack repository?

**Comment by akshaykumar0291** [comment]
Yes it is already there in my project, but still unable to add this.

**Comment by akshaykumar0291** [comment]
Hi, i don't know what happens that time, now it is working.
Thank you

**Comment by akshaykumar0291** [comment]
Could it be support to two lines different lines for two different messages.

**Comment by blennerSilva** [comment]
sorry didnt really understand your question

**Comment by akshaykumar0291** [comment]
With your popup dialog I can set only one title and one message but I need to set two message lines separate.

**Comment by nanoakhi** [comment]
ERROR: Failed to resolve: com.github.blennerSilva:AwesomeDialog:2.0.5
Show in Project Structure dialog
