### ISSUE TITLE
ERROR: Failed to resolve: com.github.blennerSilva:AwesomeDialog:2.0.5

### ISSUE THREAD

**Issue by musabeni** [blennerSilva/AwesomeDialog#23]
I got this error while sync the project "**ERROR: Failed to resolve: com.github.blennerSilva:AwesomeDialog:2.0.5**"and i have already add "maven { url "https://jitpack.io" }" in my gradle-project  am using android 3.3.1

**Comment by mehrankasebvatan** [comment]
Hi
Use this version : 2.0.6
Worked for me .

**Comment by abdallah-gaber** [comment]
Worked for me too :) Thanks @mehrankasebvatan

**Comment by musabeni** [comment]
Thanx it work

**Comment by kibugenzad** [comment]
Works for me too thanks

**Comment by mshahzaib374** [comment]
Work for me but you need to update the library version for new user
Thanks :)
