### ISSUE TITLE
Lib not found

### ISSUE THREAD

**Issue by Duna** [blennerSilva/AwesomeDialog#25]
gradle error: Failed to resolve: com.github.blennerSilva:AwesomeDialog:2.0.5

**Comment by Duna** [comment]
Android Studio 3.4 - >  all latest and greatest

**Comment by aqeel371** [comment]
using latest version does not give error implementation 'com.github.blennerSilva:AwesomeDialog:2.0.6'

**Comment by daivatsoni** [comment]
I was using Android Studio 2.3 and since i am using this module. I have updated my Android studio v3.4. It start showing BUILD error like below:
```
ERROR: Could not find AwesomeDialog.aar (com.github.blennerSilva:AwesomeDialog:2.0.5).
Searched in the following locations:
    https://jitpack.io/com/github/blennerSilva/AwesomeDialog/2.0.5/AwesomeDialog-2.0.5.aar
```
Please suggest what should I do? I am unable to work due to such a build error.

Thanks in advance.
D.

**Comment by daivatsoni** [comment]
> I was using Android Studio 2.3 and since i am using this module. I have updated my Android studio v3.4. It start showing BUILD error like below:
> 
> ```
> ERROR: Could not find AwesomeDialog.aar (com.github.blennerSilva:AwesomeDialog:2.0.5).
> Searched in the following locations:
>     https://jitpack.io/com/github/blennerSilva/AwesomeDialog/2.0.5/AwesomeDialog-2.0.5.aar
> ```
> 
> Please suggest what should I do? I am unable to work due to such a build error.
> 
> Thanks in advance.
> D.

By upgrading version to 2.0.6 for this library, resolved my issue. 
Thanks.

**Comment by Duna** [comment]
> using latest version does not give error implementation 'com.github.blennerSilva:AwesomeDialog:2.0.6'

You can close the issue

**Comment by Duna** [comment]
> using latest version does not give error implementation 'com.github.blennerSilva:AwesomeDialog:2.0.6'

You can close the issue
