### ISSUE TITLE
Can do action when the popup dismiss (backPressed) ?

### ISSUE THREAD

**Issue by Paul75** [blennerSilva/AwesomeDialog#9]
Hello,

For example i use this with camera qrcode scanner Zbar and when I press back button I must reactivate the scanner.

It works with the action of button OK i can add line to reactivate but when I can do the line when I click back to my phone when dialog is open ?

Thanks

**Comment by blennerSilva** [comment]
Right now i dont think it is posssible cuz e always dismiss it on any click. What you could do is download de code and override on backpressed inside dialog fragment it should work

**Comment by Paul75** [comment]
for exemple I use Zbar qrcode scanner and I must do after a popup close : mScannerView.resumeCameraPreview(resultHandler);

I have found a solution: .setCancelable(false) that not allow to close without a button ....

**Comment by blennerSilva** [comment]
i thought u were already using that lol but im glad it worked
